name: Node.js CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Test
      run: pnpm run lint

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Build and deploy
      run: |
        pnpm run build
        pnpm run deploy